name: Run Python Module

on:
  schedule:
    - cron: "0 * * * *"  # Ejecuta el workflow cada hora al minuto 0
  workflow_dispatch:  # Permite ejecutar manualmente el workflow desde GitHub

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Sistema operativo en el que se ejecutar치 el workflow

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Descarga el c칩digo del repositorio

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"  # Puedes cambiar a otra versi칩n si lo necesitas

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # Instala dependencias si existe `requirements.txt`

      - name: Run Python module
        run: python -m eb_leads_extraction_to_odoo  # Ejecuta el m칩dulo Python
        env: 
          IRE_URL: ${{ secrets.IRE_URL }}
          IRE_DB: ${{ secrets.IRE_DB }}
          IRE_USERNAME: ${{ secrets.IRE_USERNAME }}
          IRE_PASSWORD: ${{ secrets.IRE_PASSWORD }}

